# Generated by Django 5.1.7 on 2025-03-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ELDR', 'Earnings per Labor Dollar Rate (ELDR)'), ('RE', 'Revenue per Employee (RE)'), ('RBE', 'Revenue per Billable Employee (RBE)'), ('UBH', 'Utilization Billable Hours (UBH)'), ('UB', 'Utilization Benchmark (UB)'), ('LM', 'Labor Multiplier (LM)'), ('LMM', 'Labor Maximum Multiplier (LMM)'), ('DB', 'Days Backlog (DB)'), ('DCH', 'Days Cash on Hand (DCH)')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kpi_type', models.CharField(choices=[('number', 'Número'), ('percentage', 'Porcentaje'), ('currency', 'Moneda'), ('days', 'Días')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiInputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Fecha que representa el período (ej. 2023-05-01 para mayo 2023)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data_file', models.FileField(blank=True, null=True, upload_to='kpi_raw_data/')),
                ('file_type', models.CharField(choices=[('total', 'Total'), ('mensual', 'Mensual')], max_length=20)),
                ('total_horas_facturables', models.FloatField(blank=True, default=0, null=True)),
                ('total_horas_planta', models.FloatField(blank=True, default=0, null=True)),
                ('total_horas_facturadas', models.FloatField(blank=True, default=0, null=True)),
                ('numero_empleados', models.IntegerField(blank=True, default=0, null=True)),
                ('numero_empleados_facturables', models.IntegerField(blank=True, default=0, null=True)),
                ('dias_trabajados', models.IntegerField(blank=True, default=0, null=True)),
                ('costo_por_hora', models.FloatField(blank=True, default=0, null=True)),
                ('ganancia_total', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Datos de Entrada para KPIs',
                'ordering': ['-period'],
                'unique_together': {('period', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='CalculatedKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kpi')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_kpis', to='dashboard.kpiinputdata')),
            ],
            options={
                'verbose_name': 'KPI Calculado',
                'verbose_name_plural': 'KPIs Calculados',
                'ordering': ['kpi', 'input_data__period'],
                'unique_together': {('kpi', 'input_data')},
            },
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('target_value', models.FloatField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kpi')),
            ],
            options={
                'verbose_name': 'Objetivo de KPI',
                'ordering': ['kpi', 'period'],
                'unique_together': {('kpi', 'period')},
            },
        ),
    ]
