# Generated by Django 5.2 on 2025-04-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_kpiinputdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='name',
        ),
    ]
