# Generated by Django 5.2 on 2025-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_kpi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='data',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
