# Generated by Django 5.2 on 2025-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_kpi_data_alter_kpi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiinputdata',
            name='corresponding_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
