# Generated by Django 5.2 on 2025-05-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_kpiinputdata_corresponding_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='value',
        ),
    ]
