# Generated by Django 5.2 on 2025-05-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_kpi_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='corresponding_month',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='costo_por_hora',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='dias_trabajados',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='ganancia_total',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='numero_empleados',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='numero_empleados_facturables',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='total_horas_facturables',
        ),
        migrations.RemoveField(
            model_name='kpiinputdata',
            name='total_horas_facturadas',
        ),
    ]
