# Generated by Django 5.2.3 on 2025-06-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingresoactividad',
            unique_together=set(),
        ),
    ]
