# Generated by Django 5.2.1 on 2025-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_finantialdata_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('Envio', 'Envio'), ('Equipo', 'Equipo'), ('Ingenieria de Control', 'Ingenieria de Control'), ('PLC', 'OLC'), ('Reparacion Servidores', 'Reparacion Servidores'), ('Servicio Electrico', 'Servicio Electrico'), ('Servicio Redes', 'Servicio Redes'), ('Software (Licencias)', 'Software (Licencias)'), ('Tableros', 'Tableros'), ('Viaticos', 'Viaticos')], max_length=100)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Ingresos de Actividades',
            },
        ),
    ]
