# Generated by Django 5.2.3 on 2025-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_ingresoactividad_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoactividad',
            name='actividad',
            field=models.CharField(choices=[('Envio', 'Envio'), ('Equipo', 'Equipo'), ('Ingenieria de Control', 'Ingenieria de Control'), ('PLC', 'PLC'), ('Reparacion Servidores', 'Reparacion Servidores'), ('Servicio Electrico', 'Servicio Electrico'), ('Servicio Redes', 'Servicio Redes'), ('Software (Licencias)', 'Software (Licencias)'), ('Tableros', 'Tableros'), ('Viaticos', 'Viaticos'), ('Servicio Drives', 'Servicio Drives')], max_length=100),
        ),
    ]
