# Generated by Django 5.2.1 on 2025-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asignacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('horas_trabajadas', models.IntegerField()),
                ('empleado', models.CharField(max_length=100)),
                ('grupo_empleados', models.CharField(max_length=100)),
                ('proyecto', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('status_proyecto', models.BooleanField()),
                ('ot', models.CharField(max_length=100)),
                ('planta', models.CharField(max_length=100)),
            ],
        ),
    ]
