# Generated by Django 5.2.1 on 2025-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_registrohoras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoras',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='asignacion',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='cliente',
            new_name='employee_group',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='horas_trabajadas',
            new_name='hours_worked',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='empleado',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='status_proyecto',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='registrohoras',
            old_name='grupo_empleados',
            new_name='time_entry_status',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='task',
            field=models.CharField(default='Sin Asignación', max_length=200),
        ),
    ]
