# Generated by Django 5.1.7 on 2025-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_empleado_nombre_alter_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default='2025-03-25'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
