# Generated by Django 5.2.1 on 2025-05-15 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_empleado_facturable_remove_empleado_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='info',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
