# Generated by Django 5.2.1 on 2025-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sistemas', 'Sistemas'), ('proyectos', 'Proyectos'), ('espectador', 'Espectador')], default='espectador', max_length=50),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nomina_mensual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
