# Generated by Django 5.2 on 2025-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_empleado_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default='2025-04-28'),
        ),
    ]
