# Generated by Django 5.2 on 2025-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_empleado_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default='2025-05-12'),
        ),
    ]
